import { NgClass } from '@angular/common';
import { Component } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { GlobalConstants } from '../../common/global-constants';

@Component({
  selector: 'app-game',
  standalone: true,
  imports: [NgClass,TranslateModule],
  templateUrl: './game.component.html',
  styleUrl: './game.component.css'
})
export class GameComponent{

  public changeTextTitle : string = "Ejemplo";
  public changeTextBody : string = "Lorem";
  public learn : boolean = false;
  public currentLan : string = GlobalConstants.currentLang;

  public action_es : {t:string,b:string} = 
  {t:"ACCIONES DE JUEGO", b:"<ul><li><b>GIRAR Y ENDEREZAR:</b> Girar una carta es ponerla de lado; esto significa que se usó durante el turno. Haces esto cuando usas una tierra para producir maná, cuando atacas con una criatura o cuando activas una habilidad que tiene el símbolo como parte del coste ( significa “gira este permanente”).  Cuando se gira un permanente, no puedes girarlo de nuevo hasta que se endereza (se pone derecho de nuevo).  En cuanto empieza tu turno, endereza tus cartas giradas para que puedas usarlas de nuevo.</li><li><b>LANZAR HECHIZOS:</b> Para lanzar un hechizo, debes pagar su coste de maná (ubicado en la esquina superior derecha de la carta) girando tierras (u otros permanentes) para generar la cantidad y tipo de maná que requiere el hechizo. Por ejemplo, si fueras a lanzar el Ángel de Serra, que cuesta , podrías girar tres tierras básicas de cualquier tipo para pagar más dos Llanuras para pagar Una vez que hayas lanzado el hechizo, puede ocurrir una de estas dos cosas. Si el hechizo es un instantáneo o un conjuro, sigues las instrucciones en la carta y luego pones la carta en tu cementerio. Si el hechizo es una criatura, artefacto, encantamiento, pones la carta en la mesa frente a ti. La carta está ahora en el campo de batalla.</li></ul>"};

  public action_en : {t:string,b:string} = 
  {t:"GAME ACTIONS", b:"<ul><li><b>TURN AND UPRIGHT:</b> Turning a card is putting it sideways; this means it was used during the turn. You do this when you use a land to produce mana, when you attack with a creature, or when you activate an ability that has the symbol as part of the cost ( means “turn this permanent”). When a permanent is turned, you can't turn it again until it's upright (put upright again). As soon as your turn begins, straighten out your turned cards so you can use them again.</li><li><b>CASTING SPELLS:</b> To cast a spell, you must pay its mana cost (located in the upper right corner of the card) by turning lands (or other permanents) to generate the amount and type of mana required by the spell. For example, if you were to cast Serra Angel, which costs , you could turn three basic lands of any type to pay plus two Plains to pay Once you've cast the spell, one of two things can happen. If the spell is an instant or sorcery, follow the instructions on the card and then put the card in your graveyard. If the spell is a creature, artifact, enchantment, put the card on the table in front of you. The card is now on the battlefield.</li></ul>"};

  public atk_es : {t:string,b:string} = 
  {t:"ATACAR Y BLOQUEAR", b:"<p>La manera más común de ganar el juego es atacar con tus criaturas. Si una criatura que está atacando a un oponente no es bloqueada, le hará a ese oponente una cantidad de daño igual a su fuerza.<br>La fase que queda en medio de cada turno es la fase de combate. En tu fase de combate, eliges cuáles de tus criaturas atacarán y a qué oponentes atacarán. Gira tus criaturas para indicar que están atacando. Después, tus oponentes eligen con cuáles de sus criaturas bloquearán, si es que deciden bloquear. Las criaturas giradas no pueden ser declaradas como bloqueadoras.<br>Una vez elegidas todas las bloqueadoras, todas las criaturas (tanto atacantes como bloqueadoras) hacen simultáneamente una cantidad de daño igual a su fuerza (el número que está a la izquierda de la barra en la esquina inferior derecha de la carta).</p>"};

  public atk_en : {t:string,b:string} = 
  {t:"ATTACK AND BLOCK", b:"<p>The most common way to win the game is by attacking with your creatures. If a creature that is attacking an opponent is not blocked, it will deal damage to that opponent equal to its power.<br>The phase that occurs in the middle of each turn is the combat phase. In your combat phase, you choose which of your creatures will attack and which opponents they will attack. Tap your creatures to indicate that they are attacking. Then, your opponents choose which of their creatures will block, if they decide to block. Tapped creatures cannot be declared as blockers.<br>Once all blockers are chosen, all creatures (both attackers and blockers) simultaneously deal damage equal to their power (the number to the left of the slash in the bottom right corner of the card).</p>"};

  public turn_es : {t:string,b:string} = 
  {t:"PARTES DEL TURNO", b:"<p>Cada turno sigue la misma secuencia. Siempre que comiences un nuevo paso o fase, cualquier habilidad disparada que tenga lugar durante ese paso o fase se dispara y va a la pila.</p><b>FASE INICIAL</b><ul><li><b>Paso de enderezar:</b> Enderezas todos tus permanentes girados. En el primer turno del juego, no tienes permanentes, así que simplemente te saltas este paso. Nadie puede lanzar hechizos o activar habilidades durante este paso.</li><li><b>Paso de mantenimiento:</b> Los jugadores pueden lanzar instantáneos y activar habilidades. Esta parte del turno se menciona en algunas cartas. Si algo debe suceder una vez por turno, justo al comienzo, la habilidad se disparará “al comienzo de tu mantenimiento”.</li><li><b>Paso de robar:</b> Debes robar una carta de tu biblioteca (aunque no quieras). El jugador que comienza primero en un juego de dos jugadores se salta el paso de robar en su primer turno para compensar la ventaja de empezar primero. Luego, los jugadores pueden lanzar instantáneos y activar habilidades.</li></ul><p><b>PRIMERA FASE PRINCIPAL:</b> Puedes lanzar cualquier cantidad de conjuros, instantáneos, criaturas, artefactos, encantamientos y planeswalkers, y puedes activar habilidades. Además, puedes jugar una tierra durante esta fase, pero recuerda que solo puedes jugar una tierra durante tu turno. Tu oponente puede lanzar instantáneos y activar habilidades</p><b>FASE DE COMBATE</b><ul><li><b>Paso de inicio del combate:</b> Los jugadores pueden lanzar instantáneos y activar habilidades.</li><li><b>Paso de declarar atacantes:</b> Tú decides si alguna o varias de tus criaturas enderezadas atacarán y a qué jugador o planeswalker atacarán. Esto gira las criaturas atacantes. Luego, los jugadores pueden lanzar instantáneos y activar habilidades...</li><li><b>Paso de declarar bloqueadoras:</b> Tu oponente decide si alguna o varias de sus criaturas enderezadas bloqueará a tus criaturas atacantes. Si varias criaturas bloquean a una misma atacante, tú ordenas a las bloqueadoras para mostrar cuál será la primera que reciba daño, cuál la segunda, etcétera. Luego, los jugadores pueden lanzar instantáneos y activar habilidades.</li><li><b>Paso de final del combate:</b> Los jugadores pueden lanzar instantáneos y activar habilidades</li>"};

  public turn_en : {t:string,b:string} = 
  {t:"PARTS OF THE TURN", b:"<p>Each turn follows the same sequence. Whenever you begin a new step or phase, any triggered abilities that occur during that step or phase are put onto the stack.</p><b>INITIAL PHASE</b><ul><li><b>Untap step:</b> Untap all your tapped permanents. In the first turn of the game, you have no permanents, so you simply skip this step. No one can cast spells or activate abilities during this step.</li><li><b>Upkeep step:</b> Players can cast instants and activate abilities. This part of the turn is mentioned on some cards. If something must happen once per turn, right at the start, the ability will trigger “at the beginning of your upkeep”.</li><li><b>Draw step:</b> You must draw a card from your library (even if you don't want to). The player who goes first in a two-player game skips the draw step on their first turn to balance the advantage of going first. Then, players can cast instants and activate abilities.</li></ul><p><b>MAIN PHASE ONE:</b> You can cast any number of spells, instants, creatures, artifacts, enchantments, and planeswalkers, and you can activate abilities. Additionally, you can play a land during this phase, but remember that you can only play one land during your turn. Your opponent can cast instants and activate abilities</p><b>COMBAT PHASE</b><ul><li><b>Beginning of combat step:</b> Players can cast instants and activate abilities.</li><li><b>Declare attackers step:</b> You decide if any or several of your untapped creatures will attack and which player or planeswalker they will attack. This taps the attacking creatures. Then, players can cast instants and activate abilities...</li><li><b>Declare blockers step:</b> Your opponent decides if any or several of their untapped creatures will block your attacking creatures. If multiple creatures block a single attacker, you assign blockers to show which will be the first to receive damage, which the second, etc. Then, players can cast instants and activate abilities.</li><li><b>End of combat step:</b> Players can cast instants and activate abilities</li>"};
  public onChangeText(ampText:{t:string,b:string}){
    this.changeTextTitle = ampText.t;
    this.changeTextBody = ampText.b;
    this.learn=true;
    
  }

}
